### ISSUE TITLE
Question: Changing sub-domains

### ISSUE THREAD

**Issue by ZeroInputCtrl** [aptalca/docker-webserver#10]
I have been using this docker for a while, running it on Unraid 6. I wanted to add a subdomain so I added it to the env variable but when the container restarts the cert doesn't get renewed or recreated with the added sub-domain. How can i do this?

**Comment by aptalca** [comment]
Currently, it doesn't check for changes to the variables input. It assumes they are the same as the first install. I'll add that feature when I get a chance.

For now, you can just delete the "etc" folder in the config location and restart the container. It should create a new cert with the updated subdomains and nginx should automatically pick up the new cert. One word of caution, though. Don't do it too many times in a row because letsencrypt has limits set and they will block new requests for a period of time.

The old cert will technically still be valid as far as letsencrypt is concerned, but if you didn't make any copies, once you delete the etc folder, it will be deleted forever. You might still get an e-mail from them when it is about to expire, and you can ignore that.

**Comment by ZeroInputCtrl** [comment]
Ok that's cool thanks for the quick reply.
